# Étape 1: Construire l'application Angular
FROM node:18-alpine AS build

WORKDIR /app

# Installer les dépendances et construire l'application Angular
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Étape 2: Utiliser une image Node.js légère pour exécuter le serveur HTTP
FROM node:18-alpine

# Installer le serveur HTTP pour les fichiers statiques
RUN npm install -g http-server

# Copier les fichiers construits d'Angular dans l'image
COPY --from=build /app/dist/book-crud /app

# Exposer le port 8080 pour accéder à l'application
EXPOSE 8080

# Lancer l'application avec http-server
CMD ["http-server", "/app", "-p", "8080", "-c-1"]
